export const DELETE_PROVIDER = 'DELETE_PROVIDER';
export const CLOSE_PROVIDER = 'CLOSE_PROVIDER';

export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const CLOSE_CUSTOMER = 'CLOSE_CUSTOMER';
export const NEXT_STEP_CUSTOMERS = 'NEXT_STEP_CUSTOMERS';
export const DELETE_CAR = 'DELETE_CAR';

export const DELETE_BUDGETS = 'DELETE_BUDGETS';
export const CLOSE_BUDGETS = 'CLOSE_BUDGETS';
export const NEXT_STEP_BUDGETS = 'NEXT_STEP_BUDGETS';
export const DELETE_SERVICE = 'DELETE_SERVICE';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CLOSE_PRODUCT = 'CLOSE_PRODUCT';

export const DELETE_USER = 'DELETE_USER';
export const CLOSE_USER = 'CLOSE_USER';

export const DELETE_EMPLOYEES = 'DELETE_EMPLOYEES';
export const CLOSE_EMPLOYEES = 'CLOSE_EMPLOYEES';
