export const DELETE_PROVIDER = 'DELETE_PROVIDER';
export const CLOSE_PROVIDER = 'CLOSE_PROVIDER';

export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_BUDGETS = 'DELETE_BUDGETS';
export const DELETE_STOCK = 'DELETE_STOCK';

export const DELETE_USER = 'DELETE_USER';
export const CLOSE_USER = 'CLOSE_USER';
